#! /usr/bin/env python3
from os import environ, makedirs
from xml.etree import ElementTree
import hashlib

root = ElementTree.parse("pom.xml").getroot()
release_tag = root.find("{http://maven.apache.org/POM/4.0.0}version").text
print(release_tag)


def gen_hash(filename: str) -> str:
    sha256_hash = hashlib.sha256()
    with open(filename, "rb") as f:
        for block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(block)
    return sha256_hash.hexdigest()


checksums = [gen_hash(filename) for filename in [
    f"mcpkg-{release_tag}.jar",
    "mcpkg.sh",
    "README.md"
]]


maintainer = '# Maintainer: Ben Mitchell <bjosephmitchell@gmail.com>\n'
readme_url = f'https://raw.githubusercontent.com/CRISPYricePC/mcpkg/{release_tag}/README.md'
shell_url = f'https://raw.githubusercontent.com/CRISPYricePC/mcpkg/{release_tag}/mcpkg.sh'

opening = maintainer + '\n# This file is automatically generated. Do not edit.\n'

print('Generating PKGBUILD for mcpkg...')
makedirs('./pkgbuild/mcpkg', exist_ok=True)
with open('./pkgbuild/mcpkg/PKGBUILD', 'w') as pkgbuild:
    content = opening + '\n'
    content += 'pkgname=mcpkg\n'
    content += f'pkgver={release_tag}\n'
    source_url_prefix = 'https://github.com/CRISPYricePC/mcpkg/releases/download/${pkgver}'
    source_url = source_url_prefix + "/mcpkg-${pkgver}.jar"
    content += f"source=(\n\t{source_url}\n\tmcpkg::{shell_url}\n\tmcpkg::readme{readme_url}\n)\n"
    content += f"sha256sums=(\n"
    for sum in checksums:
        content += f"\t'{sum}'\n"
    content += f")\n"
    content += open('./ci/templates/mcpkg/PKGBUILD').read() + '\n'
    pkgbuild.write(content)
