name: Publish
on:
  release:
    types: [published, edited]

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven
      - name: Build with Maven
        run: mvn compile assembly:single --file pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: mcpkg.jar
          path: target/mcpkg*.jar

  make-pkgbuild:
    name: Create PKGBUILD
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/download-artifact@v2
        with:
          name: mcpkg.jar
      - name: Generate PKGBUILD
        run: ./ci/github-actions/generate-pkgbuild.py
      - uses: actions/upload-artifact@v2
        with:
          name: PKGBUILD
          path: pkgbuild/mcpkg-bin/PKGBUILD
      - uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        name: Publish AUR package
        with:
          pkgname: mcpkg
          pkgbuild: pkgbuild/mcpkg/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
