name: Publish
on:
  push:
    branches: [releases]

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven
      - name: Build with Maven
        run: mvn compile assembly:single --file pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: mcpkg.jar
          path: target/mcpkg*.jar

  make-pkgbuild:
    name: Create PKGBUILD
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: actions/download-artifact@v2
        with:
          name: mcpkg.jar
      - name: Generate Checksums
        run: ci/github-actions/generate-checksums.sh
      - name: Generate PKGBUILD
        run: ./ci/github-actions/generate-pkgbuild.py3
      - uses: actions/upload-artifact@v2
        with:
          name: PKGBUILD
          path: pkgbuild/mcpkg-bin/PKGBUILD
